---
title: "BST 270: Individual Project"
subtitle: "Plane Crash Figure Recreation"
author: "Ethan Lee"
format:
  html: default
  pdf:
    keep-tex: true
    include-in-header: 
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
         \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
  gfm: default
code-fold: true
---

## Plane Crashes

This script reproduces two figures from this FiveThirtyEight article [Should Travelers Avoid Flying Airlines That Have Had Crashes in the Past?
](https://fivethirtyeight.com/features/should-travelers-avoid-flying-airlines-that-have-had-crashes-in-the-past/)

## Part 1
First, load the data from 
```{r}
# Download and Read the Plane Safety Data
airplane_data <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/airline-safety/airline-safety.csv")

# Define the Path to Save the CSV File
output_dir <- "data"
output_file <- file.path(output_dir, "airplane_data.csv")

# Check if the 'data' Directory Exists; If Not, Create It
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
  message(paste("Created directory:", output_dir))
}

write.csv(airplane_data, file = output_file, quote = FALSE, row.names = FALSE)
message(paste("Data successfully written to:", output_file))
```



You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
